package com.bigsea.sns.dao.mapper.test;

import com.bigsea.sns.model.test.Demo;
import java.util.List;

public interface DemoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_test_demo
     *
     * @mbg.generated Wed Sep 20 18:58:31 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_test_demo
     *
     * @mbg.generated Wed Sep 20 18:58:31 GMT+08:00 2017
     */
    int insert(Demo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_test_demo
     *
     * @mbg.generated Wed Sep 20 18:58:31 GMT+08:00 2017
     */
    Demo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_test_demo
     *
     * @mbg.generated Wed Sep 20 18:58:31 GMT+08:00 2017
     */
    List<Demo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_test_demo
     *
     * @mbg.generated Wed Sep 20 18:58:31 GMT+08:00 2017
     */
    int updateByPrimaryKey(Demo record);
}