package com.bigsea.sns.model.test;

public class Demo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_test_demo.id
     *
     * @mbg.generated Wed Sep 20 18:58:31 GMT+08:00 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_test_demo.name
     *
     * @mbg.generated Wed Sep 20 18:58:31 GMT+08:00 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_test_demo.id
     *
     * @return the value of gen_test_demo.id
     *
     * @mbg.generated Wed Sep 20 18:58:31 GMT+08:00 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_test_demo.id
     *
     * @param id the value for gen_test_demo.id
     *
     * @mbg.generated Wed Sep 20 18:58:31 GMT+08:00 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_test_demo.name
     *
     * @return the value of gen_test_demo.name
     *
     * @mbg.generated Wed Sep 20 18:58:31 GMT+08:00 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_test_demo.name
     *
     * @param name the value for gen_test_demo.name
     *
     * @mbg.generated Wed Sep 20 18:58:31 GMT+08:00 2017
     */
    public void setName(String name) {
        this.name = name;
    }
}